In [1]:
import numpy as np
import pandas as pd

In [2]:
# 1. How likely is it that you roll doubles when rolling two dice?

n_trials = n_cols = 2
n_sims = n_rows = 100_000

dice_rolls = pd.DataFrame(np.random.choice([1, 2, 3, 4, 5, 6], size=(n_sims, n_trials)))
dice_rolls

0  1
0      1  2
1      2  6
2      3  3
3      2  1
4      1  5
...   .. ..
99995  5  2
99996  6  2
99997  4  4
99998  5  2
99999  1  2

[100000 rows x 2 columns]

In [3]:
roll_doubles = dice_rolls[0] == dice_rolls[1]
roll_doubles

0        False
1        False
2         True
3        False
4        False
         ...  
99995    False
99996    False
99997     True
99998    False
99999    False
Length: 100000, dtype: bool

In [4]:
probability_of_doubles = roll_doubles.mean()
probability_of_doubles

0.1656

In [5]:
# 2. #2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?
n_trials = 8
n_sims = 100_000

# 1 is  heads, 0 is tails
coin_flips = np.random.choice([0, 1], size=(n_sims, n_trials))
coin_flips

array([[1, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 0, 1, 0],
       [1, 1, 1, ..., 0, 1, 1],
       ...,
       [1, 0, 1, ..., 0, 1, 1],
       [0, 1, 1, ..., 0, 0, 0],
       [1, 1, 0, ..., 1, 1, 0]])

In [6]:
exactly_3_heads = (coin_flips == 1).sum(axis=1) == 3
exactly_3_heads.mean()

0.21879

In [8]:
#more_than_3_heads = (coin_flips == 1).sum(axis=1) > 3
#more_than_3_heads

more_than_3_heads.mean()


0.63619

In [9]:
# 3. There are approximitely 3 web development cohorts for every 
#1 data science cohort at Codeup. Assuming that Codeup randomly selects 
#an alumni to put on a billboard, what are the odds that the 
#two billboards I drive past both have data science students on them?

n_trials = 2
n_sims = 100_000

billboards = np.random.choice(['Web Dev', 'Data Science'], p=[.75, .25], size=(n_sims, n_trials))
billboards

array([['Web Dev', 'Web Dev'],
       ['Web Dev', 'Data Science'],
       ['Data Science', 'Web Dev'],
       ...,
       ['Web Dev', 'Web Dev'],
       ['Data Science', 'Data Science'],
       ['Web Dev', 'Web Dev']], dtype='<U12')

In [10]:
df = pd.DataFrame(billboards)
df.columns = ["first_billboard", "second_billboard"]
df.head()

first_billboard second_billboard
0         Web Dev          Web Dev
1         Web Dev     Data Science
2    Data Science          Web Dev
3         Web Dev     Data Science
4         Web Dev     Data Science

In [11]:
df["both_ds"] = (df.first_billboard == "Data Science") & (df.second_billboard == "Data Science")
df["both_ds"].mean()

0.06226

In [12]:
# 4. Codeup students buy, on average, 3 poptart packages with a standard deviation
#of 1.5 a day from the snack vending machine. If on monday the machine is restocked 
#with 17 poptart packages, how likely is it that I will be able to buy some poptarts 
#on Friday afternoon? (Remember, if you have mean and standard deviation, 
#use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

n_trials = ncols = 5
n_sims = nrows = 100_000

poptart_purchases = np.random.normal(3,1.5, size = (n_sims, n_trials))
rounded_poptart_purchases = poptart_purchases.round()
rounded_poptart_purchases

array([[ 3.,  3.,  1.,  0.,  6.],
       [-0.,  2.,  4.,  3.,  2.],
       [ 1.,  3.,  4.,  2.,  2.],
       ...,
       [ 0.,  1.,  3.,  5.,  1.],
       [ 4.,  3.,  3.,  3.,  3.],
       [ 4.,  3.,  3.,  1.,  2.]])

In [13]:
no_neg_poptarts = np.where(rounded_poptart_purchases < 0, 0, rounded_poptart_purchases)
no_neg_poptarts

array([[ 3.,  3.,  1.,  0.,  6.],
       [-0.,  2.,  4.,  3.,  2.],
       [ 1.,  3.,  4.,  2.,  2.],
       ...,
       [ 0.,  1.,  3.,  5.,  1.],
       [ 4.,  3.,  3.,  3.,  3.],
       [ 4.,  3.,  3.,  1.,  2.]])

In [14]:
poptarts_on_friday = no_neg_poptarts.sum(axis=1) < 17
poptarts_on_friday.mean()

0.67076

In [15]:
# 5. Compare heights

# Men have an average height of 178 cm and standard deviation of 8cm.
men_height = np.random.normal(178, 8, size = 100_000)
men_height

array([182.93259744, 184.79039326, 178.31570638, ..., 166.59959918,
       174.10728673, 176.0540986 ])

In [16]:
# Women have a mean of 170, sd = 6cm.
women_height = np.random.normal(170, 6, size = 100_000)
women_height

array([169.77109289, 175.14850546, 168.45954363, ..., 168.21127786,
       172.0938079 , 175.21958657])

In [ ]:
women_height = np.random.normal(170, 6, size=100_000)

In [20]:
# If a man and woman are chosen at random, P(woman taller than man)?

height = pd.DataFrame({'Average Mens Height': men_height, 'Average Womens Height': women_height})
height

Average Mens Height  Average Womens Height
0               182.932597             169.771093
1               184.790393             175.148505
2               178.315706             168.459544
3               169.403954             171.084685
4               170.709318             169.929204
...                    ...                    ...
99995           183.965387             164.037732
99996           167.251094             168.178349
99997           166.599599             168.211278
99998           174.107287             172.093808
99999           176.054099             175.219587

[100000 rows x 2 columns]

In [24]:
height['Women taller than Man'] = (height['Average Womens Height'] > height['Average Mens Height'])
height['Women taller than Man'].mean()

0.21348

In [25]:
# 6. When installing anaconda on a student's computer, 
#there's a 1 in 250 chance that the download is corrupted and 
#the installation fails. What are the odds that after having 50 students 
#download anaconda, no one has an installation issue? 100 students?

def prob_no_anaconda_corruption(students, number_of_sims_to_run):
    n_trials = n_cols = students
    n_sims = n_rows = number_of_sims_to_run

    installs = np.random.choice([0, 1], p=[1/250, 249/250], size=(n_rows, n_cols))
    
    no_corruptions = installs.sum(axis=1) == students
    
    return no_corruptions.mean()

In [26]:
prob_no_anaconda_corruption(50, 100_000)


0.81894

In [27]:
prob_no_anaconda_corruption(100, 100_000)


0.67058

In [ ]:
# What is the probability that we observe an installation issue within the first 150 students that download anaconda?

def prob_anaconda_corruption(students, number_of_sims_to_run):
    n_trials = n_cols = students
    n_sims = n_rows = number_of_sims_to_run

    installs = np.random.choice([0, 1], p=[1/250, 249/250], size=(n_rows, n_cols))
    
    has_corruptions = installs.sum(axis=1) < students
    
    return has_corruptions.mean()

In [ ]:
prob_anaconda_corruption(150, 100_000)


In [ ]:
# How likely is it that 450 students all download anaconda without an issue?

prob_anaconda_corruption(450, 100_000)
(249/250)**450

In [28]:
# 7. There's a 70% chance on any given day that there will be at least
#one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. 
#How unlikely is this?

n_trials = 3
n_sims = 100_000

# 0 is no food trucks, 1 is at least 1 food truck
food_trucks = np.random.choice([0, 1], p=[.3, .7], size=(n_sims, n_trials))
food_trucks

array([[1, 0, 1],
       [1, 0, 1],
       [1, 1, 1],
       ...,
       [1, 0, 1],
       [1, 1, 1],
       [1, 0, 0]])

In [29]:
no_food_trucks = food_trucks.sum(axis=1) == 0
no_food_trucks

array([False, False, False, ..., False, False, False])

In [30]:
no_food_trucks.mean()


0.02647

In [32]:
# Likelihood of food truck showing up sometime in a week

# How likely is it that a food truck will show up sometime this week?

n_trials = 7
n_sims = 100_000

food_trucks = np.random.choice([0, 1], p=[.3, .7], size =(n_sims, n_trials))
food_trucks


array([[1, 1, 1, ..., 1, 1, 1],
       [1, 0, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 1, 0],
       ...,
       [1, 1, 0, ..., 1, 1, 0],
       [0, 1, 0, ..., 1, 0, 1],
       [0, 1, 1, ..., 1, 1, 1]])

In [33]:
at_least_one_food_truck = food_trucks.sum(axis=1) > 0
at_least_one_food_truck.mean()

0.99976

In [34]:
# 8. If 23 people are in the same room, what are the odds that two of them share a birthday? 
#What if it's 20 people? 40?

birthdays = np.random.randint(1,365, (100_000, 23))
birthdays_df = pd.DataFrame(birthdays)
(birthdays_df.nunique(axis=1) < 23).mean()

0.50831

In [23]:
birthdays = np.random.randint(1,365, (100_000, 23))
bd_df = pd.DataFrame(birthdays)
pd.options.display.max_columns = 25
#bd_df.head()
bd_df.nunique(axis=1) #Takes all the values from column axis [axis=1] which run between 0 and 23
bd_df.nunique(axis=1) < 23 #Retruns T or F if the value on the column axis of 100,000 values that less than 23
(bd_df.nunique(axis=1) < 23).mean() #Returns the mean of the values on the column axis that were less than 23
#(bd_df.nunique(axis=1) < 20).mean()

0.50833

In [24]:
bd_df.shape

(100000, 23)

In [36]:
birthdays = np.random.randint(1,365, (100_000, 20))
birthdays_df = pd.DataFrame(birthdays)
(birthdays_df.nunique(axis=1) < 20).mean()

0.41217

In [37]:
birthdays = np.random.randint(1,365, (100_000, 40))
birthdays_df = pd.DataFrame(birthdays)
(birthdays_df.nunique(axis=1) < 40).mean()

0.89255